---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: chore

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: chore

  - package-ecosystem: "gomod"
    directories:
      - "examples/auth-nkeys"
      - "examples/auth-none"
      - "examples/auth-user-pass"
      - "examples/simple-server"
    schedule:
      interval: "daily"
    commit-message:
      prefix: chore
